### ISSUE TITLE
Hi, can you tell me that where can I get the file 'resnet50_vrd_inference.h5''?, Thank you

### ISSUE THREAD

**Issue by wenzhendeng** [pranoyr/visual-relationship-detection#1]

**Comment by pranoyr** [comment]
Added

**Comment by wenzhendeng** [comment]
Hello Pranovr, I have another question for help, how can I get the labels.csv of VRD
dataset? I use 'convert_to_csv.py' to get labels.csv, obviously, it's wrong.
