### ISSUE TITLE
The outputs are incorrect

### ISSUE THREAD

**Issue by Rubatoo** [pranoyr/visual-relationship-detection#6]
Hi
Text is not coming out of the output image.
what should i do?
![8544815951_de514c0305_b](https://user-images.githubusercontent.com/64789592/87953838-83c16580-cae6-11ea-91ad-a86869f0dde3.jpg)

**Comment by pranoyr** [comment]
which version of tensorflo are you using?

**Comment by Rubatoo** [comment]
i'm using tensorflow 2.2.0

**Comment by pranoyr** [comment]
Use Tensorflow 1.5. The RetinaNet uses TF 1.5

**Comment by djkim3** [comment]
Which keras version?
I installed keras 2.3 and tensorflow-gpu 1.15
When i downgrade tensorflow 1.5, code isn't work
